name: CI on PR

on: [ pull_request ]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Checkout code into workspace directory
        uses: actions/checkout@v3

      - name: Install all Go dependencies
        run: go mod vendor

      - name: Build
        run: go build -o main

      - name: Test
        working-directory: ./backend/src
        run: make test

  Linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code into workspace directory
        uses: actions/checkout@v3

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
