name: CI on PR

on: [ pull_request ]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run vendor
        run: go mod vendor

      - name: Build
        run: |
          go build -o bin/refresh_hash_worker ./cmd/refresh_hash_worker
          go build -o bin/http_api ./cmd/http_api
          go build -o bin/grpc_api ./cmd/grpc_api
          go build -o bin/grpc_client ./cmd/grpc_client

      - name: Test
        run: make test

  Linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
